import { EvmChainId } from "../../src/chain/evm/index.js";

const NATIVE_CURRENCIES = {
  [EvmChainId.ETHEREUM]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.SEPOLIA]: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.GÖRLI]: { name: "Görli Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.POLYGON]: { name: "MATIC", symbol: "MATIC", decimals: 18 },
  [EvmChainId.POLYGON_TESTNET]: {
    name: "MATIC",
    symbol: "MATIC",
    decimals: 18,
  },
  [EvmChainId.FANTOM]: { name: "Fantom", symbol: "FTM", decimals: 18 },
  [EvmChainId.FANTOM_TESTNET]: { name: "Fantom", symbol: "FTM", decimals: 18 },
  [EvmChainId.GNOSIS]: { name: "xDAI", symbol: "XDAI", decimals: 18 },
  [EvmChainId.BSC]: { name: "BNB", symbol: "BNB", decimals: 18 },
  [EvmChainId.BSC_TESTNET]: { name: "BNB", symbol: "BNB", decimals: 18 },
  [EvmChainId.ARBITRUM]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.ARBITRUM_NOVA]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.ARBITRUM_TESTNET]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.AVALANCHE]: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
  [EvmChainId.AVALANCHE_TESTNET]: {
    name: "Avalanche",
    symbol: "AVAX",
    decimals: 18,
  },
  [EvmChainId.HECO]: { name: "HT", symbol: "HT", decimals: 18 },
  [EvmChainId.HARMONY]: { name: "ONE", symbol: "ONE", decimals: 18 },
  [EvmChainId.OKEX]: { name: "OKT", symbol: "OKT", decimals: 18 },
  [EvmChainId.CELO]: { name: "CELO", symbol: "CELO", decimals: 18 },
  [EvmChainId.PALM]: { name: "PALM", symbol: "PALM", decimals: 18 },
  [EvmChainId.MOONRIVER]: { name: "Moonriver", symbol: "MOVR", decimals: 18 },
  [EvmChainId.FUSE]: { name: "FUSE", symbol: "FUSE", decimals: 18 },
  [EvmChainId.TELOS]: { name: "TLOS", symbol: "TLOS", decimals: 18 },
  [EvmChainId.MOONBEAM]: { name: "GLMR", symbol: "GLMR", decimals: 18 },
  [EvmChainId.OPTIMISM]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.KAVA]: { name: "KAVA", symbol: "KAVA", decimals: 18 },
  [EvmChainId.METIS]: { name: "Metis", symbol: "METIS", decimals: 18 },
  [EvmChainId.BOBA]: { name: "Boba", symbol: "BOBA", decimals: 18 },
  [EvmChainId.BOBA_AVAX]: { name: "Boba", symbol: "BOBA", decimals: 18 },
  [EvmChainId.BOBA_BNB]: { name: "Boba", symbol: "BOBA", decimals: 18 },
  [EvmChainId.BTTC]: { name: "BTT", symbol: "BTT", decimals: 18 },
  [EvmChainId.BASE_TESTNET]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.POLYGON_ZKEVM]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.THUNDERCORE]: {
    name: "Thunder Token",
    symbol: "TT",
    decimals: 18,
  },
  [EvmChainId.FILECOIN]: { name: "Filecoin", symbol: "FIL", decimals: 18 },
  [EvmChainId.HAQQ]: { name: "Islamic Coin", symbol: "ISLM", decimals: 18 },
  [EvmChainId.CORE]: { name: "CORE", symbol: "CORE", decimals: 18 },
  [EvmChainId.ZKSYNC_ERA]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.LINEA]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.BASE]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.BASE_SEPOLIA]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.SCROLL]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.ZETACHAIN]: { name: "ZETA", symbol: "ZETA", decimals: 18 },
  [EvmChainId.CRONOS]: { name: "Cronos", symbol: "CRO", decimals: 18 },
  [EvmChainId.BLAST]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.SKALE_EUROPA]: { name: "SKALE", symbol: "SKL", decimals: 18 },
  [EvmChainId.ROOTSTOCK]: { name: "RSK Bitcoin", symbol: "RBTC", decimals: 18 },
  [EvmChainId.MANTLE]: { name: "Mantle", symbol: "MNT", decimals: 18 },
  [EvmChainId.CURTIS]: { name: "Curtis", symbol: "CURT", decimals: 18 },
  [EvmChainId.MANTA]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.MODE]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.TAIKO]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.ZKLINK]: { name: "Ether", symbol: "ETH", decimals: 18 },
  [EvmChainId.APE]: { name: "APE", symbol: "APE", decimals: 18 },
  [EvmChainId.SONIC]: { name: "SONIC", symbol: "SONIC", decimals: 18 },
  [EvmChainId.HEMI]: { name: "HEMI", symbol: "HEMI", decimals: 18 },
  [EvmChainId.SHIBARIUM]: { name: "BONE", symbol: "BONE", decimals: 18 },
  [EvmChainId.PUPPYNET]: { name: "BONE", symbol: "BONE", decimals: 18 },
};

export const TEST_CHAIN_DATA = Object.entries(NATIVE_CURRENCIES).map(
  ([chainId, nativeCurrency]) => ({
    chainId: Number(chainId),
    nativeCurrency,
  })
);
